platformName: Android
#模拟器
#platformVersion: 5.1.1
#deviceName: 127.0.0.1:62001

#HUAWEI P7
#platformVersion: 4.4.2
#udid: 7N2RDQ149T026117
#deviceName: HUAWEI P7

#Redmi Note 4X
#platformVersion: 6.0
#udid: YS55VOYDS88SDQ9T
#deviceName: Redmi Note 4X

#HUAWEI P20
platformVersion: 10.0.0
udid: CLB0218615004786
deviceName: HUAWEI P20

#HUAWEI P20 无线连接模式
#platformVersion: 10.0.0
#deviceName: 10.1.101.229:5555

appname: life_v1.0.18_2020-10-31_18_preview6.apk
#启动app时不要清除app里的原有的数据
#noReset: False
noReset: True
ANDROID_UIAUTOMATOR: uiautomator2
unicodeKeyboard: True
resetKeyboard: True
appPackage: com.fanda.chungoulife
appActivity: com.ddz.component.welcome.WelcomeActivity
chromedriverUseSystemExecutable: True
ip: 127.0.0.1
port: 4723